### ISSUE TITLE
生成的.d.map文件路径不正确.

### ISSUE THREAD

**Issue by BigMango** [qmhc/vite-plugin-dts#112]
基于1.5.0的测试(以前的也不行).
在vscode中,如果生成一个库给app用,如果库附带源代码.在tsconfig中打开 declarationMap.
运行 pnpm test:e2e.
plugin.ts会报错,修改一下可以运行了.
```diff
-compilerOptions.rootDir ||= root
+compilerOptions.rootDir = compilerOptions.rootDir || root;
```
生成的dist/components/DefaultImport.vue.d.ts.map的情况如下:
```
"sourceRoot":"",
"sources":["DefaultImport.vue.ts"]
```
tsconfig中增加 "sourceRoot": "."的情况如下
```
"sourceRoot":"./",
"sources":["src/components/DefaultImport.vue.ts"]
```
app中引用库后,vscode无法定位到interface类型的源代码,只能导航到相应的 .d.ts 文件

正确的路径应该是.
```
"sourceRoot":"../../",
"sources":["src/components/DefaultImport.vue.ts"]
```
或者
```
"sourceRoot":".",
"sources":["../../src/components/DefaultImport.vue.ts"]
```

是插件的问题,还是配置问题呢

**Comment by qmhc** [comment]
经过考虑，map 文件路径就算正确也无法指向回 vue 文件，所以目前先不支持 map 功能了。

**Comment by cchanche** [comment]
From what I could translate, it seems `declarationMap`s are not yet supported, is that correct ? I see @qmhc you added a milestone for this earlier, does this mean the feature is to be included in the next release ?

This is quite a deal breaker for our library since `declarationMap`s are a very handy feature for DX.

I came across the exact same problem as @BigMango and solved it by using rollup plugins. My solution is a bit _hacky_, and I would love to have this implemented here instead.

**Comment by qmhc** [comment]
@cchanche The main problem is how to map to vue soruce file.
