### ISSUE TITLE
Unable to use in a monorepo (yarn workspaces)

### ISSUE THREAD

**Issue by spaceemotion** [qmhc/vite-plugin-dts#14]
The following line breaks the package in a monorepo setup:

https://github.com/qmhc/vite-plugin-dts/blob/main/src/index.ts#L162

Yarn (workspaces) puts the dependencies at the project root, and not besides each package (to reduce duplications).

I was able to "fix" this for our setup via the `nohoist` option in yarn.

Is there a reason for using `resolve` and not just a plain `require('@vue/compiler-sfc)`?

Cheers!

**Comment by qmhc** [comment]
In my case, I set `root` option to the monorepo root dir, because this can generate full declarations when a package references other packages. Combining with bundle declarations tools like `@microsoft/api-extractor`, can finally generate a single declaration file.

Monorepo has a lot of variables that may need to be manually config to some extent.

Hope my practice can provide some help for you.

For single bundling each package, this issue is a problem, I will fix it later.
