### ISSUE TITLE
dts doesn't resolve typescript paths on dts generation and wrong dts dist structure

### ISSUE THREAD

**Issue by D4RKAR117** [qmhc/vite-plugin-dts#19]
Hello I'm trying to generate the .d.ts for my vite vue lib, but at the time that i inspect my dist folder i identify 2 problems so far:

1. the .ts based .d.ts such as index.d.ts doesn't resolve correctly the typescript paths. eg. '@/' path. So module not found problem raises at the import and export of anything.

2. The dist folder gets the intended declaration dir (in my case @types/), but have an incorrect folder structure for d.ts of my components. like copying the src/ dir inside. This maybe works alongside a  correr path resolution buy i have no clue about it.

i have no idea if I'm misunderstanding something, or i have a wrong configuration for proper generation of types of my lib, so any advice is appreciated  

For reproduction :
- clone the repo: https://github.com/D4RKAR117/vuestraped at branch 'development' 
- npm install
- npm run build
- verify the generated dist directory and its inner structure

**Comment by qmhc** [comment]
The directory structure relative to `root` will be maintained when generating declaration files. This is to ensure the correct relationship of each type reference.

If you want a fixed export entry, you can use the `insertTypesEntry` option, otherwise you need to specify the type entry with `types` option in `package.json`.

In your case, first you need to remove `declarationDir` option in `tsconfig.json` (using `outputDir` instead) and change `src/@types/index.d.ts` to `src/@types/index.ts` (currently not support import type from `.d.ts` file), then add `outputDir: '@types'` to plugin options and run build script, finally add `"types": "@types/src/index.d.ts"` into `package.json`.

![image](https://user-images.githubusercontent.com/40221744/129431017-4a07f262-0baa-4c05-a894-e4ac97a7e545.png)

If you want to generate only a single declaration file in the end, I recommend `@microsoft/api-extractor` to you, use it after running build script to bundle declaration files.

**Comment by qmhc** [comment]
I will add support for import types from `.d.ts` files later.

**Comment by D4RKAR117** [comment]
Thanks for the fast answer, and the great advices.

The generation is much better with the changes made [in this commit](https://github.com/D4RKAR117/vuestraped/commit/e07702d9c6289d9a508ee849007bc22d5755fb2e)

also idk if is intended that @types is generated out `dist` with your advice, so y made `outputDir` to point inside `dist`, but maybe i misunderstood that part.

but my playground still failing with the import at `src/index.d.ts`. The typescript path `@component` is not resolved when is generated. Still like `import VContainer from '@components/layout/container/VContainer.vue';`. if this is related to the support that still WIP i will change to relative paths, but i like to have your confirmation first.

Thanks.

**Comment by qmhc** [comment]
There have some bugs, I open a new issue (#20) to track them.

Now you can change your alias config:

```ts
defineConfig({
  resolve: {
    alias: {
      '@components': path.resolve(__dirname, 'src/components'),
      '@': path.resolve(__dirname, 'src')
    }
  }
})
```

And use `import { default as VContainer } from '@/components/layout/container/VContainer.vue'` to solve this problem.
