### ISSUE TITLE
Support TypeScript 5 and other TypeScript versions

### ISSUE THREAD

**Issue by corsen2000** [qmhc/vite-plugin-dts#194]
### Description

As a developer using vite-plugin-dts I would like to use TypeScript 5. In particular, I'd like to use `moduleResolution: bundler`, which was added in that release.

vite-plugin-dts currently uses `"@microsoft/api-extractor`. Unfortunately, this package comes with a specific version of TypeScript. At the time of wring, that version is `~4.8.4`.

### Suggested solution

if https://github.com/microsoft/rushstack/pull/3891 on `@microsoft/api-extractor` is merged, then we, in theory, would be able to use any version of TypeScript. I'm unsure if additional code changes may be required in this repository. Unfortunately this PR looks stalled.

### Alternative

It may be possible to stop using `@microsoft/api-extractor` and use the TypeScript API or CLI directly. In one project, I've worked around this by removing vite-plugin-dts and using `tsc` directly. This works for a basic `vite build` but not so nicely with `vite build --watch`.

### Additional context

There is an overlap between this issue and #190, but I thought it was worth filing separately.

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by elboletaire** [comment]
Weird, I actually ended up here because I'm 100% sure this plugin is using version 5.* instead of the installed version 4.* and I need a way to properly force it using the installed version.

If you're wondering how am I so sure, it's easy: building with version 4.* I got no errors, whilst building with version 5.* returns me multiple "Expression produces a union type that is too complex to represent" errors:

**tsc 4 build:**
![ts 4](https://user-images.githubusercontent.com/153305/232479018-e4133857-50eb-4e0e-843b-dc8710a4e2cc.png)

**tsc 5 build:**
![ts 5](https://user-images.githubusercontent.com/153305/232478796-34d0ab31-a85a-4fbd-bb47-bb5a68b58092.png)

**vite-plugin-dts build:**
![vite-plugin-dts](https://user-images.githubusercontent.com/153305/232479134-e602d988-8041-4fb1-86be-ccff2442f93c.png)

Is that api-extractor plugin the one responsible for getting the proper typescript version? If so, there may be a bug there (or a missing param set, haven't checked their docs), because I already have vscode configured to use the locally installed version of typescript, and using vscode scripts properly uses my installed 4.* version.

I'm only experiencing this issue since vscode upgraded typescript to version 5, which makes me think the issue is related.

**Comment by Tanimodori** [comment]
[API Extractor 7.35.0 was recently released using TypeScript ~5.0.4](https://github.com/microsoft/rushstack/issues/3890#issuecomment-1560292185)  (see PR https://github.com/microsoft/rushstack/pull/4103). Is there any plan to upgrade to TS 5? @qmhc
