### ISSUE TITLE
use unplugin implement more build tool to use 

### ISSUE THREAD

**Issue by bigbigDreamer** [qmhc/vite-plugin-dts#214]
### Description

I found that compared to the `dts` generation of `rollup`, this tool is relatively outstanding. Thanks to the author's hard work, I would like to ask if it is possible to provide a solution similar to [unplugin](https://github.com/unjs/unplugin), such as a plugin, which can also be used in `rollup`.

### Suggested solution

/

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by sxzz** [comment]
@qmhc Seems like #226 didn't include unplugin. Is this issue really resolved?

**Comment by qmhc** [comment]
@sxzz Yes, by the description, the real issue is supporting Rollup. Is there a need to use the plugin on other scaffold?

**Comment by bigbigDreamer** [comment]
My basic need is rollup. I haven't had time to experience it yet. I saw the beta version some time ago, but it seems to serve more building tools from the perspective of unplugin.

**Comment by qmhc** [comment]
@bigbigDreamer Well. when I was preparing to develop v3, I want to use `uplugin`. But I ran into a bottleneck when parsing some scaffold's config (entry, default outDir, aliases, etc...), due to the above. For fast, so I rolled back to normal vite plugin and made it support Rollup.

If some needs, I will reconsider migrating to unplugin. 😁
