### ISSUE TITLE
Upgrade @microsoft/api-extractor@7.43.0 to latest so latest typescript version can be used

### ISSUE THREAD

**Issue by darcyparker** [qmhc/vite-plugin-dts#359]
### Describe the bug

Can `vite-plugin-dts` specify `"@microsoft/api-extractor": "^7.47.4"` so that updating to latest typescript is feasible?

`vite-plugin-dts@3.9.1` (same with 4.0 beta), depends on`@microsoft/api-extractor@7.43.0`, which depends on `typescript@5.4.2`.  And I am seeing the following message:

### Steps to reproduce

`tsc && vite build`

And I am seeing the following message:

```
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.4.2
*** The target project appears to use TypeScript 5.5.4 which is newer than the bundled compiler engine; consider upgrading API Extractor.
```

### System Info

FYI `npm list typescript` shows it is the only package in my project that has `5.4.2`. 

```
├─┬ vite-plugin-dts@3.9.1
│ ├─┬ @microsoft/api-extractor@7.43.0
│ │ └── typescript@5.4.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by darcyparker** [comment]
Is this patch holding things back? https://github.com/qmhc/vite-plugin-dts/blob/main/package.json#L114

**Comment by alSergey** [comment]
Hi, I'm also concerned about this issue. Maybe there is a way to remove the hard link with @microsoft/api-extractor? I would like to be able to update TypeScript without waiting for vite-plugin-dts to update.

**Comment by elkofy** [comment]
I ran into the same issue what do you advise to do I have been stuck for 4 days on this

**Comment by qmhc** [comment]
The latest version has used `@microsoft/api-extractor@7.47.4`.

**Comment by alSergey** [comment]
@qmhc hi, updating `@microsoft/api-extractor` to the `latest` version does not solve the problem. Tomorrow a new version of typescript is released and we again cannot update because of a hard link to `@microsoft/api-extractor`. Maybe there is a way to add `@microsoft/api-extractor` as a peerDependencies or add `^`?

**Comment by bisubus** [comment]
@qmhc Can this issue stay open for now? This looks like long-running problem because `@microsoft/api-extractor` has a restriction on typescript version. The latest ts version is 5.5.4 and api-extractor still uses 5.4.2. I assume it may have some problems with 5.5 but if that's the case, more specific errors would be more helpful rather than the use of unsynced ts versions through the project.

The current workaround is to make api-extractor a direct dependency to hoist it in node_modules and make it more predictable:

```
npm i -D typescript@5.5.4 vite-plugin-dts@4.0.3 @microsoft/api-extractor@7.47.7
```

And use the overrides in package.json:

```
  "overrides": {
    "@microsoft/api-extractor": {
      "typescript": "$typescript"
    }
  },
  "resolutions": {
    "@microsoft/api-extractor/**/typescript": "*"
  },
  "pnpm": {
    "overrides": {
      "@microsoft/api-extractor>typescript": "$typescript"
    }
  }
```

No luck for Bun https://github.com/oven-sh/bun/issues/6608 so it has to rely on lockfile from other PMs.

**Comment by elkofy** [comment]
> @qmhc Can this issue stay open for now? This looks like long-running problem because `@microsoft/api-extractor` has a restriction on typescript version. The latest ts version is 5.5.4 and api-extractor still uses 5.4.2. I assume it may have some problems with 5.5 but if that's the case, more specific errors would be more helpful rather than the use of unsynced ts versions through the project.
> 
> The current workaround is to make api-extractor a direct dependency to hoist it in node_modules and make it more predictable:
> 
> ```
> npm i -D typescript@5.5.4 vite-plugin-dts@4.0.3 @microsoft/api-extractor@7.47.7
> ```
> 
> And use the overrides in package.json:
> 
> ```
>   "overrides": {
>     "@microsoft/api-extractor": {
>       "typescript": "$typescript"
>     }
>   },
>   "resolutions": {
>     "@microsoft/api-extractor/**/typescript": "*"
>   },
>   "pnpm": {
>     "overrides": {
>       "@microsoft/api-extractor>typescript": "$typescript"
>     }
>   }
> ```
> 
> pnpm seems to have problems with deeply nested overrides, so it benefits from hoisted dep. And Bun doesn't support nested ones at all [oven-sh/bun#6608](https://github.com/oven-sh/bun/issues/6608) , it has to rely on lockfile from other PMs.

How this would work with yarn ?

**Comment by bisubus** [comment]
@elkofy Seems to be ok, "resolutions" entry handles it
